### ISSUE TITLE
Strip Git repo

### ISSUE THREAD

**Issue by alecandido** [ElStabilini/optimization#19]
So, now that the `main` branch has been reorganized, we could forget about the past. But since Git doesn't love to forget on its own, and it zealously holds all your changes, we need to convince it to release those large files which are now affecting the size of the repo (the `.git/` folder).

### The quick way

Since we don't care particularly about the history, a quick way of downsizing the repo is just cutting its history.

How to do that? Let's face first the case of only `main` present.

Essentially, I'm repeating what is also written in [this SO answer](https://stackoverflow.com/a/11688066/8653979), with some additional explanation.

Let's assume that this is our history:
```
A -- B -- C -- D -- E -- F
```
and we'd like to achieve this:
```
D -- E -- F
```

This is what the mentioned answer is proposing:
```sh
# create a new branch with D's content
$ git checkout --orphan temp <d-sha1>
$ git commit

# rebase everything else onto the temp branch
$ git rebase --onto temp <d-sha1> master

# clean up
$ git checkout master
$ git branch -d temp
```

In practice, we do not need to keep any history, and because of the recent merges it would be complicated to rebase (possible, but complicate, since we don't have the simple linear history outlined above), so we will preserve only the last commit (the equivalent of F)

#### Our solution (<-- use this)

Here the battle-tested solution:
```sh
git checkout --orphan temp
git commit  # below the suggested commit message, keep reading

git branch -D main
git switch -c main
git branch -D temp

git push --force-with-lease
```

As mentioned above, this is the solution if a single branch is present. If you still have multiple ones (because you want to do this before merging existing PRs, to restart keeping the history asap), here are the most practical solutions:
1. forget about that, and wait for all the existing PRs to be merged :P
2. repeat the operation above for each branch (not sure how GitHub will react for PRs based on orphaned branches, but we will discover ^^)
3. one branch at a time:
   - check out the branch (`git switch mybranch`), and copy its content in a folder outside the repo
   - switch back to `main` (`git switch main`)
   - delete the branch (`git branch -D mybranch`)
   - recreate the branch from main (`git switch -C mybranch`)
   - move back that content copied, and commit it

The last two solutions will preserve **only the last commit**, as we did for `main` (but it's one commit more for each branch than the first one, and you can safely keep building on top of that).

##### Suggested commit message
```
chore: Cut the repository history

This has been necessary to drop some large files accidentally commited
in at a previous stage.
Alternatives have been considered, including:

- filtering out only the irrelevant and heavy files
- preserve part of the history

but they have been discarded, as not very practical for the current
state of the repo, nor necessarily required, given the limited relevance
of the history.
```
To insert it, just use `git commit` (as shown above), and your default editor will open: copy the message and save the file (then you can close the editor).

Of course, feel free to change it as you prefer.

#### Clean-up

I assume GitHub will do its clean-up on its own (once all the branches will be cut to the last commit, or deleted).

So, locally, you have two options:
- delete the repo, and clone it again
- keep going with the SO answer above, and do:
    ```sh
    # if needed, first remove all outdated remote branches with
    # git branch -D --remote origin/outdated-branch1 origin/outdated-branch2 ...

    git reflog expire --expire=now --all
    git gc --prune=now
    ```

This will finally save you ~2.4 GB (i.e. the current entire size of the repo).

### The expert - and useless - way (*don't do this*)

> useless in this case

For the sake of everyone's knowledge (and nothing else), be aware that the Git objects are just weirdly-named files[*] (blobs), copies of the individual files you see in the folder, which are mentioned in other files (tree, more or less directories represented as lists) which are mentioned in other files (other trees, or commits), with daisy-chained commits (mentioning other commits, and so on), eventually referred by the "refs" (such as the `main` branch, which is nothing else than a file containing the reference to a single commit).

This to say that in principle you may just scan these files manually, and modify the commits and trees to change the history.

A more practical way is to use tools that have been written specifically for that. [`git filter-branch`](https://git-scm.com/docs/git-filter-branch) should have been that tool, the one shipped with the original Git distribution, but it's slow, unsafe, and cumbersome.
Instead, there are third-party tools which are way more recommended, e.g. [`git filter-repo`](https://github.com/newren/git-filter-repo/). To learn more, I advise reading its README.

In any case, with the help of this tool we could delete only some files, selecting them with globs and regexes. This is uselessly complex in this case, so let's forget for this time.

[*]: plus some additional appliances known as pack files - only understand that they pack many diffs into a single file (they are used for optimizing storage, but let's ignore them at this level)

**Comment by ElStabilini** [comment]
### Strip git repo

Thank you @alecandido, I followed your instructions and should have correctly stripped the repo. 
Regarding the unmerged branches I chose to proceed as suggested in 2, so

>  repeat the operation above for each branch

Apparently the on PR was simply closed  by GitHub.

There's just one thing I did differently but should be fine from what I read around, when running 

`git push --force-with-lease`

I got the error message

`To https://github.com/ElStabilini/optimization.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/ElStabilini/optimization.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.`

So I run 

`git push --set-upstream origin main --force-with-lease`

and worked out smoothly.

### Clean up

I simply removed the local folder and cloned it again

**Comment by alecandido** [comment]
The operation was generally successful
```nu
╭───┬──────────────┬──────────┬──────────╮
│ # │     path     │ apparent │ physical │
├───┼──────────────┼──────────┼──────────┤
│ 0 │ .git         │  2.3 MiB │  2.4 MiB │
│ 1 │ opt_analysis │  3.4 MiB │  3.5 MiB │
╰───┴──────────────┴──────────┴──────────╯
```

But now you need to fix the bases branch of all the other existing branches in order to make them ahead of `main`.

This should be possible just doing:
```sh
git switch <my-branch>
git rebase main
```

Unfortunately, there will be conflicts, and these conflicts will have to be fixed manually.

> [!NOTE]
> *I've not been clear enough on option 2 above, my bad 🙇. This could have been partially avoided by just rebasing the commits that before were ahead of `main` onto the new `main` - now there is no way other than fixing the conflicts. But hopefully it will be mostly an automatic step.*

**Comment by ElStabilini** [comment]
I succesfully rebased all the branches to main following the above instructions.

I will close the issue with this comment, thank you @alecandido for your support.
