### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by alecandido** [ElStabilini/optimization#6]
Things like [`__pycache__`](https://github.com/ElStabilini/optimization/tree/983e68da12f3d15d5dcb12cefc0e96eef4fbdbff/__pycache__) folders (and its content) are automatically generated[*]. In general, you should aim to only save in a repo the content you write, or, more precisely, what is needed to reproduce your runs[**].

So, there are files called `.gitignore` that you can use to instruct Git to avoid tracking that content by accident. The syntax is pretty intuitive, but it's easier to learn from the examples:
https://github.com/github/gitignore/blob/main/Python.gitignore
(which is the same of [Qibocal's `.gitignore](https://github.com/qiboteam/qibocal/blob/main/.gitignore) - unless they updated it)

However, that file is huge, and contains a lot of unneeded entries. I would suggest instead to just take a look to it and keep the lines that are matching some of the files that you have in your repo.

[*]: moreover, in the specific case of Python, they also depend on the specific Python version and implementation. So, it's even more useless to store/share them
[**]: ok, I'm personally against storing data in repos, but that's also quite personal, since you need to manage them somehow, and the alternatives are not often as simple

**Comment by ElStabilini** [comment]
At this point where I already have different branches, where should I create the `.gitignore` file?

I tried to create one, it should work
[gitignore.docx](https://github.com/user-attachments/files/17529495/gitignore.docx)

(.docx extension only to be able to upload it)

**Comment by alecandido** [comment]
> (.docx extension only to be able to upload it)

(on systems other than Windows you don't need an extension for a file - however, since even GitHub propagates this limitation, for generic text files use `.txt`, which is just that: a text file ^^)

> At this point where I already have different branches, where should I create the `.gitignore` file?

In general, switch to `main`, branch off that, commit your `.gitignore`, and open a new PR. I will make a few comments, but that's more an exercise about PRs. In this case, `main` would have been perfect, and then you can merge/rebase your other branches on top of `main` (i.e. for the time being merge `main` in the other branches, going to those branches and calling `git merge main` - I will explain you more about rebase later on, which can be confusing at the beginning).

**Comment by ElStabilini** [comment]
Thank you @alecandido, now I should have correctly added the `.gitignore` file to all the branches
